### ISSUE TITLE
Sonarr issue - Season - Episode Files - Media Info - Video Codec

### ISSUE THREAD

**Issue by OrangeJas** [OFark/Compressarr#3] opened 2021-11-01 17:08 UTC
The application give the error: **An error has occurred. This application may no longer respond until reloaded. Reload**
When I select the option: **Season - Episode Files - Media Info - Video Codec**

Here is a log file with **Trace Debuging** enabled.
[log-20211101.txt](https://github.com/OFark/Compressarr/files/7454969/log-20211101.txt)

**Comment by OFark** [comment] 2021-11-01 20:54
This USED to be an issue but I squashed that a while back, what version are you running? (Options page, at the bottom, send me all of the info)

**Comment by OrangeJas** [comment] 2021-11-01 20:54
Application: 1.2.7926.14953

Runtime: 5.0.9

FFmpeg: N-101934-g7e241a1

Docker: Yes

OS: Unix 5.10.28.0 - Nvidia HW Support

OS 64bit: True

App 64bit: True

**Comment by OFark** [comment] 2021-11-01 21:15
You said in the initial post that the Trace Debugging was enabled, there should be more in the logs, if that's the case. Can you restart the app, reproduce the error and send me the log again, it should output the "Property Name" which is causing this issue, just before it crashes.

If you're not seeing any more in the log can you send me the "Logging" part of the appsettings.json please?

**Comment by OrangeJas** [comment] 2021-11-01 21:21
[log-20211101.txt](https://github.com/OFark/Compressarr/files/7456180/log-20211101.txt)
[appsettings.txt](https://github.com/OFark/Compressarr/files/7456188/appsettings.txt)

Here are the 2 files since the log seemed the same had to change the JSON to TXT to add it in the comment.
Also I blanked some info the API keys and such.

**Comment by OFark** [comment] 2021-11-01 23:20
Can you change the Logging File Section to this:
`"File": {
      "PathFormat": "/config/logs/log-{Date}.txt",
      "LogLevel": {
        "Default": "Warning",
        "Compressarr": "Debug"
      }
    }`

Restart the app, recreate the issue and send me the log file again please.

**Comment by OrangeJas** [comment] 2021-11-01 23:29
[log-20211101.txt](https://github.com/OFark/Compressarr/files/7456674/log-20211101.txt)
Here you go

**Comment by OFark** [comment] 2021-11-01 23:36
Somethings not right, with debug logging enabled that log file should be a lot bigger than that.
Looks like your running this on Unraid. Can you restart the app repeat the crash and send me the Docker Log, please?

Looks like your 3 hours behind UTC, according to the log files, is that correct?

**Comment by OrangeJas** [comment] 2021-11-01 23:58
Yes that is correct currently I'm in UTC -3
It's also running on Unraid 6.9.2

Hopefully this one helps you
[64cd51cdbb7cdf12acc08607e012e9bdcb18d323de840ac9a9db138660e42aa0-json.txt](https://github.com/OFark/Compressarr/files/7456770/64cd51cdbb7cdf12acc08607e012e9bdcb18d323de840ac9a9db138660e42aa0-json.txt)

**Comment by OFark** [comment] 2021-11-02 09:14
That log makes much more sense. Was that the Docker Log?

I have just pushed a new version, (may take a minute to build & show up) This won't fix the problem but I have added code to, hopefully, make it fail a bit more gracefully and also log in more detail what is missing. 

What's odd id it looks like, from the original error message that the problem is you don't have any series information from Sonarr, but you couldn't get to that part of the code if you didn't. Then the remaining option is the filter is somehow returning no results, but then again the filters a built from the data, so that should also be impossible. <Head scratcher>

Just out of curiosity:

- What codec are you filtering on?
- Do the other codec options work?
- Do other filters work ok?

**Comment by OrangeJas** [comment] 2021-11-02 17:42
New version info:
> Application: 1.2.7976.16488
> Runtime: 5.0.11
> FFmpeg: N-101934-g7e241a1
> Docker: Yes
> OS: Unix 5.10.28.0 - Nvidia HW Support
> OS 64bit: True
> App 64bit: True

- What codec are you filtering on?
    I can't select an option it crashes has soon that I select the Video Codec or Audio Codec options.
- Do the other codec options work?
    Can't test see answer from question 1. 
- Do other filters work ok?
    All other filters seem ok from a quick test except the 2 codec options.

Here is a copy of the current app settings
[appsettings.txt](https://github.com/OFark/Compressarr/files/7462934/appsettings.txt)

Here is a copy of the log file for the app. But it seems still lacking.
[log-20211102.txt](https://github.com/OFark/Compressarr/files/7462908/log-20211102.txt)

Here is a copy of the docker log file.
[653e1487b6cb6268585090412b574a6796d0f068abcc15d8226dd973983b2b8c-json.txt](https://github.com/OFark/Compressarr/files/7462933/653e1487b6cb6268585090412b574a6796d0f068abcc15d8226dd973983b2b8c-json.txt)

**Comment by OFark** [comment] 2021-11-02 23:18
I have just pushed another update. I'm hoping what will happen is the page will no longer throw an error, but the drop down you get may (probably will) be empty. Let me know. 

On the left hand side of the Sonarr page, are you seeing the codex against the series?
![image](https://user-images.githubusercontent.com/4558132/139964985-b02b2939-439a-41af-be93-505e38985989.png)

**Comment by OrangeJas** [comment] 2021-11-02 23:51
If I hit refresh I can see the codecs.
Also it still gives me the error on the page when I select either codecs filter options.

Could the number of files be a potential issues.

Here are copies of the new logs:
[log-20211102.txt](https://github.com/OFark/Compressarr/files/7464606/log-20211102.txt)
[a59587a433963b9adf52f74750d733f196c971f6bd1aa9124a3c9775c1a41d96-json.txt](https://github.com/OFark/Compressarr/files/7464607/a59587a433963b9adf52f74750d733f196c971f6bd1aa9124a3c9775c1a41d96-json.txt)

The app settings didn't change.

Version: 
> Application: 1.2.7976.41956
> Runtime: 5.0.11
> FFmpeg: N-101934-g7e241a1
> Docker: Yes
> OS: Unix 5.10.28.0 - Nvidia HW Support
> OS 64bit: True
> App 64bit: True

**Comment by OFark** [comment] 2021-11-03 11:57
Version number should definitely have changed, it's based on date and time of build. No the number of files would not be the issue here, unless maybe there are no files. The problem is somewhere between taking the list of all your files, and then creating a distinct list of the codecs used something is returning an empty (null) response, that's what the "Object reference not set to an instance of an object" means.

You said "If I hit refresh I can see the codecs." Does this mean that when the page first loads there are no codecs listed next to your series?

**Comment by OrangeJas** [comment] 2021-11-03 16:29
When I initially load the Sonarr page I don't see anything on the left till I click the refresh button at the top right.

Before I clicked refreshed:
![image](https://user-images.githubusercontent.com/1713015/140101864-362b2ae4-c364-4989-b907-fa5776a5c7f1.png)

After I clicked refreshed:
![image](https://user-images.githubusercontent.com/1713015/140102141-b9effc65-4ffd-4545-a988-074ce0da9494.png)

**Comment by OFark** [comment] 2021-11-03 20:25
The green refresh button?

**Comment by OrangeJas** [comment] 2021-11-03 20:27
Yes

**Comment by OFark** [comment] 2021-11-03 20:28
Ok, that's weird, has it always done that?

**Comment by OrangeJas** [comment] 2021-11-03 21:06
Yes since I started using it's been doing that.

**Comment by OFark** [comment] 2021-11-03 21:31
What version of Sonarr are you using?

**Comment by OrangeJas** [comment] 2021-11-03 21:33
Version 3.0.4.1126
Package Version 3.0.4.1126-1 by sonarr-phantom
Mono Version 6.12.0
AppData directory /config
Startup directory /usr/lib/sonarr/bin
Mode Console

**Comment by OFark** [comment] 2021-11-03 21:38
I guess it still crashes after you've refreshed?

**Comment by OrangeJas** [comment] 2021-11-03 21:38
yes that is correct.

**Comment by OFark** [comment] 2021-11-03 21:39
Ok, I'll have a look at the way it fetches data tomorrow. It's a weird one.

**Comment by OrangeJas** [comment] 2021-11-03 21:40
Alright let me know if you want me to test anything

**Comment by OFark** [comment] 2021-11-03 23:29
Might have just fixed it with the latest update. Try it in a few minutes.

**Comment by OrangeJas** [comment] 2021-11-03 23:41
So it's better now. I can select a codec. But it crashes when I click add.

![image](https://user-images.githubusercontent.com/1713015/140233652-ba7dd29c-c9eb-4aa0-9797-8fb7dec21f46.png)

Version:
> Application: 1.2.7977.42314
> Runtime: 5.0.11
> FFmpeg: N-101934-g7e241a1
> Docker: Yes
> OS: Unix 5.10.28.0 - Nvidia HW Support
> OS 64bit: True
> App 64bit: True

Here are the log files:
[13129d481425edd0bfac78295d2793ef7c2abdaec377fe373e7e6f754f7dde07-json.txt](https://github.com/OFark/Compressarr/files/7471315/13129d481425edd0bfac78295d2793ef7c2abdaec377fe373e7e6f754f7dde07-json.txt)
[log-20211103.txt](https://github.com/OFark/Compressarr/files/7471316/log-20211103.txt)

**Comment by OFark** [comment] 2021-11-04 08:41
I think I've figured out what the problem is, somewhere along the line one or more of your files is missing information from Sonarr, or Sonarr is providing incomplete info. I've added a work around for this, but I have a feeling even if this works we've not seen the end if it.

**Comment by OrangeJas** [comment] 2021-11-04 10:11
Well I was able to create the list and then the job also.

The list of shows is populated without me clicking the green refresh button now.

**Comment by OFark** [comment] 2021-11-04 17:27
Wonderful, re-open if you run into any more issues with it. :)

**Closed as completed by OFark** 2021-11-04 17:27 UTC
